Refactor
ahmed-ismaeil/Front-End-test pull request #3
Opened 2020-03-31 23:00 UTC by ahmed-ismaeil

- added favicon
- modified styles
- more components
- rebuild text messages
- rebuild messages with a button

2020-04-05 13:42 UTC, MarcMagdi requested changes
Can we refactor the components to use hooks? 
The two hooks you'll mainly need is useEffect & useState

2020-04-05 13:42 UTC, MarcMagdi commented on src/Components/ChatRoom/index.js
>          <MyBigMsg />
Shouldn't MyBigMsg appear first in the order as it's before the two other messages?

2020-04-08 06:25 UTC, MarcMagdi approved these changes

2020-04-08 06:25 UTC, MarcMagdi commented
@ahmed-ismaeil Great Job :1st_place_medal:

2020-04-08 07:16 UTC, ahmed-ismaeil commented
> @ahmed-ismaeil Great Job 🥇

@MarcMagdi Thank you

2020-04-08 12:38 UTC, merged